학식/열람실 API 카카오톡 챗봇에서 사용 가능하도록 반영
weehan-dev/hy-chatbot pull request #2
Opened 2019-11-03 09:25 UTC by Neulhan

2019-11-03 21:21 UTC, changhoi commented on src/routers/v1/index.js
> +import libSeat from './libSeat';
변수명은 웬만하면 줄이지 않는게 좋아! 가독성이 더 중요하기 때문에
이 경우에는 meal or diet / seat or librarySeat이 좋을 것 같음

2019-11-03 21:21 UTC, changhoi commented on src/routers/v1/libSeat.js
> +
`serviceSeat` 하나에서 두 함수를 가져와야 해.
`serviceSeat.fetch` 하나, `serviceSeat.seatDataBuilder` 정도가 괜찮을 것 같은데 변수 명은 더 직관적이라고 생각되는 걸로 해도 좋아

2019-11-03 21:21 UTC, changhoi commented on src/routers/v1/libSeat.js
> +});
```
router.get('', async (req, res) => {
	try {
		const [내용1, 내용2] = await serviceSeat.fetch(req.query.version);
		const ret = serviceSeat.seatDataBuilder(내용1, 내용2);
		res.json(ret);
	} catch (e) {
		// 실패했을 경우
	}
}
```

1. GET /get 형태는 RESTFul 하지 않아서 위 같은 엔드포인트가 더 적절. RestAPI가 뭔지 Resource 부분에서 찾아 읽어봐
2. Promise를 사용할 때 컨트롤러 로직은 async await을 사용하는 경우가 더 직관적인 편이라, 해당 문법을 사용하면 좋겠고, Promise 예외처리도 Promise.then.catch 형태로 되어야 해서 문법도 틀린 것 같다. Promise 부분 문법 한 번 더 공부해봐
3. text[0], text[1] 보다는 Destructuring 사용하고 명확한 변수명을 적어주는 게 더 좋을 것 같다

2019-11-03 21:21 UTC, changhoi commented on src/routers/v1/sMeal.js
> +import serMakeSMealResponse from '../../services/serMakeSMeal';
위와 마찬가지

2019-11-03 21:21 UTC, changhoi commented on src/routers/v1/sMeal.js
> +});
위와 마찬가지

2019-11-03 21:21 UTC, changhoi requested changes
테스트 코드도 작성해서 코드리뷰 한 부분 다시 한 번 확인해줘!

2019-11-05 10:54 UTC, changhoi approved these changes
변수명 바꾸기, configs로 url 관리, chaining이 너무 깊은 문제 이유가 뭔지 더 나은 방법이 있을지 댓글로 달아주면 감사

2019-11-05 10:54 UTC, changhoi commented on src/services/serLibrarySeats.js
> +  let url = 'https://lib.hanyang.ac.kr/smufu-api/pc/1/rooms-at-seat';
URL은 configs에서 하나로 관리하는 걸로 합시다
src폴더 최상단에 configs폴더 만들고 아래 index.js에다가 관리해서 불러오는 식으로!

2019-11-05 10:54 UTC, changhoi commented on src/services/serLibrarySeats.js
> +    for(let i=0; i<data.data.data.totalCount; i++)
data.data.data.totalCount는 break 되기 쉬워 보인다.
이거는 왜 이런거야?

2019-11-05 10:54 UTC, changhoi commented on src/services/serUnivDiets.js
> +    const sMeal = await axios.get(url);
변수명 수정 부탁

2019-11-05 10:55 UTC, changhoi requested changes
객체 chaining이 왜이렇게 깊은지, 중간에 하나라도 undefined인 데이터가 있으면 에러뜸 에러처리를 해주든지 chaining을 줄일 수 있으면 줄이자

2019-11-05 18:42 UTC, Neulhan commented on src/services/serLibrarySeats.js
> +    for(let i=0; i<data.data.data.totalCount; i++)
_onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl: 'https://lib.hanyang.ac.kr/smufu-api/pc/1/rooms-at-seat' },
     [Symbol(isCorked)]: false,
     [Symbol(outHeadersKey)]:
      [Object: null prototype] { accept: [Array], 'user-agent': [Array], host: [Array] } },
  data:
   { success: true,
     code: 'success.retrieved',
     message: 'Retrieved successfully.',
     data: { totalCount: 8, list: [Array] } } }

저 한양대 열람실 API 자체가 depth가 되게 깊은 json을 주더라고여 맨 앞 data는 인자인데 변수명을 data로 썼더니 더 헷갈리게 보였네요

2019-11-06 02:44 UTC, changhoi commented on src/services/serLibrarySeats.js
> +    for(let i=0; i<data.data.data.totalCount; i++)
맨 처음 data는 axios 형식이라 그런듯 (`data.data`까지는 있을 것)
근데 그 뒤로 data는 `success === true`인 경우에만 올 수도 있어서 그 부분을 분기해주거나, `try { } catch (e) { }`로 데이터가 없을 때 에러처리 할 수있게 하는게 좋을 것같아

2019-11-07 17:12 UTC, closed without merging